// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziicwpsdumwvwjmxyisi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppaWN3cHNkdW13dndqbXh5aXNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDk2NjMsImV4cCI6MjA2MDIyNTY2M30.O_dexkKXZtRBoFE1GMknZy1JmCXPgNmgeoOIXoOhkp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);